name: Build Tweak
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Theos environment
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          curl -L "https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz" -o iPhoneOS14.5.sdk.tar.xz
          mkdir -p ~/theos/sdks
          tar -xf iPhoneOS14.5.sdk.tar.xz -C ~/theos/sdks
          echo "THEOS=~/theos" >> $GITHUB_ENV
          echo "~/theos/bin" >> $GITHUB_PATH

      - name: Build debian package
        run: |
          make package FINALPACKAGE=1
          
      - name: Save compiled file
        uses: actions/upload-artifact@v4
        with:
          name: Tweak-Output
          path: packages/*.deb
