name: Build Tweak
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos and SDK
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          # دابەزاندنا SDK ژ لینکەکێ باوەرپێکری و قایم
          curl -LO https://github.com/theos/sdks/raw/master/iPhoneOS13.0.sdk.tar.xz
          mkdir -p ~/theos/sdks
          tar -xvf iPhoneOS13.0.sdk.tar.xz -C ~/theos/sdks
          echo "THEOS=~/theos" >> $GITHUB_ENV
          echo "~/theos/bin" >> $GITHUB_PATH

      - name: Build Package
        run: |
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WelcomeTweak-Final-DEB
          path: packages/*.deb
